---
url: http://definery.io/
title: definery
description: description
keywords: think of keywords
phone: 9492908989
trackingID: UA-77714389-1
logo: img/logo_1000x1000.jpg
share: img/1200x630.jpg
repo: http://www.github.com/acidjazz/definery
